FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y git tmux vim curl wget ca-certificates build-essential cmake --no-install-recommends && \
    apt-get clean

# ROOT 
ARG ROOT_VERSION=6.24.02
RUN apt-get update && apt-get install -y dpkg-dev cmake g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev python libssl-dev && \
    apt-get install -y gfortran libpcre3-dev xlibmesa-glu-dev libglew1.5-dev libftgl-dev libmysqlclient-dev libfftw3-dev libcfitsio-dev \
    graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl0-dev qtwebengine5-dev && \
    apt-get clean
RUN wget https://root.cern/download/root_v${ROOT_VERSION}.Linux-ubuntu20-x86_64-gcc9.3.tar.gz -O root_v${ROOT_VERSION}.tar.gz && mkdir -p /root_v${ROOT_VERSION} && \
    tar -xzvf root_v${ROOT_VERSION}.tar.gz -C /root_v${ROOT_VERSION} && rm root_v${ROOT_VERSION}.tar.gz && echo "source /root_v${ROOT_VERSION}/root/bin/thisroot.sh" >> ~/.bashrc

    
# GEANT4
ARG GEANT4_VERSION=10.7.4
RUN apt-get update && apt-get install -y libexpat-dev expat libxmu-dev && \
    apt-get clean
RUN curl -L https://github.com/Geant4/geant4/archive/refs/tags/v${GEANT4_VERSION}.tar.gz --output geant4.tar.gz && \
    tar -xzf geant4.tar.gz && rm geant4.tar.gz
WORKDIR /
RUN mkdir -p /{geant4-${GEANT4_VERSION}-build,geant4-${GEANT4_VERSION}-install}
WORKDIR /geant4-${GEANT4_VERSION}-build

# For more info about build options see: https://indico.cern.ch/event/679723/contributions/2792554/attachments/1559217/2453759/Geant4InstallationGuide.pdf Section 2.3
RUN cmake -DCMAKE_INSTALL_PREFIX=/geant4-${GEANT4_VERSION}-install /geant4-${GEANT4_VERSION} \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo -DGEANT4_BUILD_MULTITHREADED=ON -DGEANT4_USE_RAYTRACER_X11=ON \
    -DGEANT4_INSTALL_DATA=ON -DGEANT4_BUILD_EXAMPLES=ON -DGEANT4_BUILD_TESTS=ON -DGEANT4_BUILD_VERBOSE_CODE=ON \
    -DGEANT4_USE_OPENGL_X11=ON -DGEANT4_USE_QT=ON && make -j6 && make install

WORKDIR /geant4-${GEANT4_VERSION}-install/share/Geant4-${GEANT4_VERSION}/data
RUN echo "Now downloading low energy nuclear data files"
RUN echo "Now downloading low energy nuclear data files"
RUN wget -m gdo-nuclear.ucllnl.org:LEND_GND1.3  
RUN wget -m gdo-nuclear.ucllnl.org:LEND_GND0.1 
RUN tar -xvf gdo-nuclear.ucllnl.org/LEND_GND1.3/LEND_GND1.3_ENDF.BVII.1.tar.gz -C /geant4-${GEANT4_VERSION}-install/share/Geant4-${GEANT4_VERSION}/data/ && \
    tar -xvf gdo-nuclear.ucllnl.org/LEND_GND0.1/ENDF.B-VII.0.tar.gz && tar -xvf gdo-nuclear.ucllnl.org/LEND_GND0.1/ENDF.B-VII.0.withDelayed.tar.gz && tar -xvf gdo-nuclear.ucllnl.org/LEND_GND0.1/ENDL99.1.tar.gz && \
    rm -rf gdo-nuclear.ucllnl.org/
ENV G4LENDDATA=/geant4-${GEANT4_VERSION}-install/share/Geant4-${GEANT4_VERSION}/data/LEND_GND1.3_ENDF.BVII.1
    
RUN echo "source /geant4-${GEANT4_VERSION}-install/bin/geant4.sh" >> ~/.bashrc && \
    echo "set -g mouse on" > /root/.tmux.conf
RUN rm -rf /geant4-${GEANT4_VERSION}-build
WORKDIR /